import { chakra, ModalContent as ModalContentUI } from '@chakra-ui/react'

export const ModalContent = chakra(ModalContentUI, {
  baseStyle: {
    _before: {
      content: '""',
      position: 'absolute',
      width: '1200px',
      height: '1200px',
      borderTopLeftRadius: '40%',
      borderTopRightRadius: '45%',
      borderBottomLeftRadius: '35%',
      borderBottomRightRadius: '40%',
      left: '60%',
      bottom: '-35%',
      backgroundColor: 'rgba(69, 105, 144, 0.15)',
      zIndex: '-1',
      animationDuration: '6s',
      animationTimingFunction: 'linear',
      animationDelay: '0s',
      animationIterationCount: 'infinite',
      animationDirection: 'normal',
      animationFillMode: 'none',
      animationPlayState: 'running',
      animationName: 'wawes',
    },
    _after: {
      content: '""',
      position: 'absolute',
      width: '1200px',
      height: '1200px',
      borderTopLeftRadius: '50%',
      borderTopRightRadius: '40%',
      borderBottomLeftRadius: '45%',
      borderBottomRightRadius: '45%',
      left: '63%',
      bottom: '-30%',
      backgroundColor: 'rgba(69, 105, 144, 0.25)',
      zIndex: '-1',
      animationDuration: '6s',
      animationTimingFunction: 'linear',
      animationDelay: '0s',
      animationIterationCount: 'infinite',
      animationDirection: 'normal',
      animationFillMode: 'none',
      animationPlayState: 'running',
      animationName: 'wawes',
    },
  },
})
